version: "2"
services:
  zipapi:
    image: docker.io/yottadb/yottadb-base 
    container_name: "zipapi"
    networks:
      - flask
    volumes:
      - "$PWD/code:/home/zipcode"
    ports:
      - 5000:5000
    entrypoint:
      - "/home/zipcode/entrypoint.sh"

networks:
    flask:
