FROM docker.io/yottadb/yottadb-base
ENV FLASK_APP=index
ENV FLASK_ENV=development
COPY index.py /tmp/index.py
COPY 2022_Gaz_zcta_national.txt /tmp/2022_Gaz_zcta_national.txt
COPY zipimport.m /tmp/zipimport.m  
SHELL ["/bin/bash", "-c"] 
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-dev python3-setuptools libffi-dev && \
    pip3 install flask && \
    /opt/yottadb/current/ydb && \
    cp /tmp/zipimport.m /data/r && \
    mkdir /home/zipcode && \
    cp /tmp/2022_Gaz_zcta_national.txt /home/zipcode && \
    cp /tmp/index.py /home/zipcode && \
    /opt/yottadb/current/ydb -run 'START^zipimport' && \
    source /opt/yottadb/current/ydb_env_set && \
    pip install yottadb && \
    rm /tmp/index.py && \
    rm /tmp/zipimport.m && \
    rm /tmp/2022_Gaz_zcta_national.txt
WORKDIR /home/zipcode
ENTRYPOINT /bin/bash -c 'source /opt/yottadb/current/ydb_env_set && flask run --host=0.0.0.0'
